---
title: "Home"
---

<style>
.leaflet {
    margin: auto;
}
</style>

```{r}
#| fig-cap: "Countries of the World"
#| fig-height: 3
#| fig-align: center
#| message: false

library(rnaturalearth) # natural earth data

library(sf) # simple (spatial) features

library(sp) # spatial data

library(leaflet) # beautiful maps

mapdata <- ne_countries(scale = "medium", # medium scale
                        returnclass = "sf") # as sf object

mapdata <- mapdata %>% 
  sf::st_transform('+proj=longlat +datum=WGS84') # re-project

leaflet() %>%
  setView(0, 0, zoom = 1.5) %>%
  addProviderTiles(providers$Esri.WorldImagery) %>%
  addPolygons(data = mapdata, 
              fillOpacity = .0, 
              weight = 2,
              color = "#009edb", 
              label = mapdata$name,
              highlightOptions = highlightOptions(color = "red", 
                                                  weight = 2,
                                                  bringToFront = TRUE)) 

```

My interests are in developing more knowledge to reduce violence against children and Adverse Childhood Experiences (ACEs), with the aim of improving child and family well-being. It is my hope that a better understanding of how to reduce violence against children, and how to reduce ACEs, will contribute to a better understanding of how to improve mental health and well-being across the lifespan. In this research I try to understand the family and community origins of aggression, antisocial behavior, anxiety and depression across different communities and contexts. My current research focuses on parenting and child development using international data. I try to understand these issues within the context of current conversations about children’s rights.

A particular focus of my work has been to examine the outcomes of physical punishment. 

> "Corporal punishment is the most common form of violence against children worldwide, leading to the injury and death of thousands of children each year. Its very widespread social acceptance means that a level of violence in childrearing is normalised, entrenching children’s low status and paving the way for other forms of violence and mistreatment." [@CP10KeyMessages2022]

> "The magnitude of violence against children is staggering. Globally, the most pervasive form of violence against children is corporal punishment. Because it often occurs in the confines of homes and other settings where children live, study and play, it is largely hidden and challenging to detect. Worldwide, it is estimated that nearly one billion children are hit, slapped, spanked, pinched, or otherwise physically punished regularly by their parents, caregivers, teachers, or other trusted adults, the same individuals responsible for nurturing, protecting, and educating them [@UNICEF2017; @WHO2020]." [@StewartTufescu2023]

More broadly, @UNICEF2024 Reports:

> "1.6 billion children (2 in 3) regularly face violent punishment at home; more than two thirds are subjected to both physical punishment and psychological aggression."

Our meta-analytic review of 50 years of research on the outcomes of physical punishment [@Gershoff2016] demonstrated that physical punishment is associated with a wide variety of negative outcomes [[*learn more*](https://agrogan1.github.io/research/cp/CP-meta.html)], and has been part of several national level policy discussions on parenting. In 2018, the American Academy of Pediatrics passed a policy statement discouraging the use of physical punishment of children [@Sege2019]. Our meta-analysis was cited in that policy statement. Referring to our work, the policy statement indicated that "A 2016 meta-analysis showed that current literature does not support the finding of benefit from physical punishment in the long-term." Similarly, in early 2019, the American Psychological Association also passed a resolution discouraging the use of physical punishment [@AmericanPsychologicalAssociation2019]. This policy statement also cited our meta-analysis.

Some research suggests that spanking should be classified as an Adverse Child Experience [@Ma2021; @Merrick2017; @Afifi2017], and that the effects of spanking may persist well into adulthood [@Gershoff2016; @Merrick2017; @Afifi2017]. Additional quantitative work has demonstrated that the effects of spanking are evident even in contexts when physical punishment is used minimally, or when used in ostensibly "normative" ways. In a number of papers, we have investigated these associations [across different communities and countries](research.qmd). Lastly, in additional papers, we have worked to demonstrate more "causally robust" associations between physical punishment and undesirable child outcomes using a variety of quantitative methods [e.g. @Cuartas2020; @GroganKaylor2004; @GroganKaylor2005; @Ma2018; @Ward2020].

A more recent stream of research pays particular attention to parenting and child development [across low and middle income countries (LMIC's)](research.qmd#multiple-indicator-cluster-surveys-mics-unicef-data). Countries that are not high-income countries are under-represented in current social research [@Henrich2010], particularly research on parenting and child development [@Draper2022]. We have examined the degree to which the association of particular parental discipline behaviors with child outcomes varies across a large number of countries. We have found some modest between country variation in these associations, but more importantly, have found a large degree of *consistency* in the degree to which parenting is associated with child outcomes across countries [@Pace2019; @Ward2023]. 

In this new stream of research, we examine a broader range of parenting behaviors, with a particular emphasis on "positive parenting" strategies [e.g. @Ward2022LCA; @Ward2023]. From this research, a positive discipline behavior that has emerged as being associated with better child outcomes is "explain[ing] why (child)’s behaviour was wrong." [@Ward2023]

Further, we are beginning to examine the association of more macro-level, or structural, factors with parenting and children's outcomes. Most recently we have been focusing on the association of gender inequality with physical abuse, parental discipline, and child outcomes [@Ma2022; @Ward2024].

I teach courses mostly in the area of statistics, quantitative methods and data visualization.





