---
title: "Research on Parenting, and Statistical Materials"
author: "Andrew Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  bookdown::gitbook:
    highlight: haddock
    css: styles.css
    github-repo: "agrogan1/agrogan1.github.io"
    split_by: none
  html_document:
    highlight: haddock
    number_sections: yes
    theme: default
    css: styles.css
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
  pagedown::html_paged: 
    highlight: haddock
    toc: yes
    number_sections: yes
    theme: default
  tint::tintHtml:
    highlight: haddock
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      fig.margin = TRUE)

```

# "Blog-ish" Posts

* [posts](https://agrogan1.github.io/myposts/)

# Research on Parenting

* [Data Visualization](https://agrogan1.github.io/MICS1/) for "Spanking and young children's socioemotional development in low- and middle-income countries"
* [Research On Corporal Punishment](https://agroganweb.wordpress.com/research-on-corporal-punishment/)
* Data Visualization of [Country Level Bans on Corporal Punishment](https://agrogan1.github.io/research/cpbans/)

# R Materials

* *Introduction to R*: 
     + [HTML Web Book](http://www-personal.umich.edu/~agrogan/R/background.html) 
     + [PDF](http://www-personal.umich.edu/~agrogan/R/introduction-to-R.pdf) 
     + [epub](http://www-personal.umich.edu/~agrogan/R/introduction-to-R.epub)
* *Quick Introduction to ggplot2*: 
     + [HTML Web Book](http://www-personal.umich.edu/~agrogan/quick-intro-ggplot2/ggplot-in-3-easy-steps-maybe-2-easy-steps.html) 
     + [PDF](http://www-personal.umich.edu/~agrogan/quick-intro-ggplot2/quick-intro-to-ggplot2.pdf)
     + [epub](http://www-personal.umich.edu/~agrogan/quick-intro-ggplot2/quick-intro-to-ggplot2.epub)
* University of Michigan colors for R Graphs: 
     + [web page](http://www-personal.umich.edu/~agrogan/R/Michigan_Colors.html) 
     + [R package](https://agrogan1.github.io/michigancolors/)
* *Two Page R*: 
     + [PDF](https://agrogan1.github.io/docs/R/two_page_R.pdf)
* *Two Page ggplot2*: 
     + [PDF](https://agrogan1.github.io/docs/ggplot2/two_page_ggplot2.pdf)
* *Five Page dplyr*:
     + [PDF](https://agrogan1.github.io/docs/dplyr/five-page-dplyr.pdf)
     + [HTML](https://agrogan1.github.io/docs/dplyr/five-page-dplyr.html)
* *Comparing Program Outcomes with ggplot2* 
     + [HTML](https://agrogan1.github.io/myposts/comparing-program-outcomes-with-ggplot2.html)

# Stata Materials

* *Two Page Stata*: 
     + [HTML](http://www-personal.umich.edu/~agrogan/stata/TwoPageStata.html) 
     + [PDF](http://www-personal.umich.edu/~agrogan/stata/TwoPageStata.pdf)
     + [epub](http://www-personal.umich.edu/~agrogan/stata/TwoPageStata.epub)
* ["Michigan Graph Scheme" for Stata](https://agroganweb.wordpress.com/michigan-graph-scheme-for-stata/)
* [Better Graphing in Stata](https://agrogan1.github.io/stata/stata-graphing/)
* [Miscellaneous Stata Programs](https://agrogan1.github.io/stata/)

# Bayesian Statistics

* [Demonstration of Bayesian Ideas](https://agrogan.shinyapps.io/shinyBayes/)
* [Bayesian Calculations](https://agrogan1.github.io/bayes/) [[Draft Interactive Version](https://agrogan.shinyapps.io/shinyBayes2/)]

# Statistical Visualizations

* [Cohen's d Calculator](https://agrogan.shinyapps.io/effect_size_calculator/)

# Data Visualization

* [How to Choose a Chart: A Visual Guide](http://www-personal.umich.edu/~agrogan/how_to_choose_a_chart/how_to_choose_a_chart_a_visual_guide.pdf). [[Extended Version](http://www-personal.umich.edu/~agrogan/how_to_choose_a_chart/how_to_choose_a_chart_v3.html)]
* [Variables and Visualization](https://agrogan1.github.io/dataviz/variables-and-visualization/variables-and-visualization.html#/)
* [Graphing Change Over Time](https://agrogan1.github.io/dataviz/graphing-change-over-time/index.html) [[PDF](https://agrogan1.github.io/dataviz/graphing-change-over-time/index.pdf)]

# Created By 

Andrew Grogan-Kaylor

* [https://umich.edu/~agrogan](https://umich.edu/~agrogan) 
* [agrogan@umich.edu](agrogan@umich.edu)




