---
title: "Interactions Are Symmetric"
author: "Andy Grogan-Kaylor" 
date: "2025-6-9"
categories: [stats, teaching]
draft: true
---

```{r}

library(plotly)

library(ggplot2)

library(crosstalk)

# library(car)

# N <- 100

x <- rep(seq(1:5), 2) # sequence from 1 to 5

m <- rep(seq(from=0, to=1), each=5) # binomial moderator

# e <- rnorm(N, 0, 10)

y <- x + m + .5 * x * m 

# m <- factor(m)

# scatter3d(x = x, y = m, z = y)

mydata <- data.frame(x, m , y)

shared_mydata <- SharedData$new(mydata)

```

```{r}

p1 <- plot_ly(data = shared_mydata, 
              x = ~x, 
              y = ~y,
              color = ~factor(m), 
              colors = "Set1",
              text = ~paste("x:", x, 
                            '<br>m:', m),
              hoverinfo = 'text',
              mode = 'lines+markers',
              marker = list(size = 10))

# p1

```

```{r}

p2 <- plot_ly(data = shared_mydata, 
              x = ~m, 
              y = ~y,
              color = ~factor(x), 
              colors = "Set1",
              text = ~paste("x:", x, 
                            '<br>m:', m),
              hoverinfo = 'text',
              mode = 'lines+markers',
              marker = list(size = 10))

# p2

```

```{r}

mytable <- DT::datatable(shared_mydata)

```


```{r}
#| column: page

# mytable

bscols(mytable, p1, p2)

```

