---
title: "Working With Dates in Stata"
author: "Andrew Grogan-Kaylor"
date: "2023-10-20"
categories: [stats]
---

# Introduction

```{r, echo=FALSE}

library(Statamarkdown)

```

Dates in any statistical software (Stata, R) are complicated. 

For example, a particular date could be coded as "4-5-2021", or "5-4-2021" or "April 5, 2021" or "5APR2021". 

In addition to the multiplicity of possible formats it is also difficult to do calculations on these kinds of quantities e.g. "How many days have elapsed from Day A to Day B?" 

To address these issues, Stata wants these dates to be encoded as a *number*, specifically the number of days since January 1, 1960. We then make sure to format these numbers as dates.

# Get The Data

```{stata, collectcode=TRUE, echo=TRUE}

use simulated-date.dta, clear

```

# List And Describe The Data

We see that both date variables are formatted as strings

```{stata, echo=TRUE}

list

describe

```

# Create Date Variables

> There are *many* date functions in Stata, to work with different kinds of data in different formats. `help date` should direct you to the documentation for *Date and time functions*.

```{stata, collectcode=TRUE, echo=TRUE}

generate startdate2 = date(startdate, "YMD") // create a date, specifying order of elements

generate enddate2 = date(enddate, "YMD") // create a date, specifying order of elements

```

> The command has created 2 dates in numeric form, but they display as numbers.

```{stata, echo=TRUE}

describe

list

```

# Format As Dates

We format these *numeric* variables as *dates*. While the variables remain as the number of days since January 1, 1960, since they are formatted as dates, they now appear as human readable dates.

```{stata, collectcode=TRUE, echo=TRUE}

format %d startdate2 enddate2
	
describe

list

```

# Calculations

We can now use dates in calculations. For example, "How much time has elapsed between `startdate2` and `enddate2`?"	

```{stata, echo=TRUE}

generate elapseddays = enddate2 - startdate2
	
generate elapsedyears = (enddate2 - startdate2)/365
	
list, abbreviate(15) // list out the data with new variables

```




	
	




	
