---
title: "Bar Charts to Pie Charts: Another Look"
author: "Andy Grogan-Kaylor"
date: "2023-9-9"
categories: [stats, dataviz]
echo: true
code-fold: true
code-summary: "Show the code"
---

# Background

A quick look at moving from bar charts to pie charts. 

A longer explanation of some issues is here: [https://agrogan1.github.io/posts/bar-charts-in-ggplot2/](https://agrogan1.github.io/posts/bar-charts-in-ggplot2/)

# Get Data

```{r}

load("social-service-agency.RData")

```

```{r, echo=FALSE}

library(dplyr)

clients <- clients %>% select(age, program, gender)

```

```{r, echo=FALSE}

library(pander)

pander(head(clients))

```

# Call `ggplot`

```{r}

library(ggplot2)

```

# One Dimension of Data (program)

## Bar Chart

```{r}

ggplot(clients, # data I am using
       aes(x = program, # x is program
           fill = program)) + # fill is also program
  geom_bar() # use bars

```

## Stacked Bar Chart

```{r}

ggplot(clients, # data I am using
       aes(x = 1, # x is now 1 for everyone
           fill = program)) + # fill is program
  geom_bar() # use bars

```

## Pie Chart

```{r}

ggplot(clients, # data I am using
       aes(x = 1, # x is now 1 for everyone
           fill = program)) + # fill is program
  geom_bar() + # use bars
  coord_polar(theta = "y") + # use polar coordinates
  theme_void() # blank theme for pie charts

```

# Two Dimensions of Data (program X gender)

## Stacked Bar Chart

```{r}

ggplot(clients, # data I am using
       aes(x = program, # x is back to program
           fill = gender)) + # fill is gender
  geom_bar() # use bars

```

## Unstack the Bars

```{r}

ggplot(clients, # data I am using
       aes(x = program, # x is back to program
           fill = gender)) + # fill is gender
  geom_bar(position = "dodge2") # unstack ('dodge') the bars

```

## Pie Chart

One approach ...

```{r}

# position = position_fill() makes the slices
# fill the pie in each facet

ggplot(clients, # data I am using
       aes(x = 1, # x is back to 1
           fill = gender)) + # fill is gender
  geom_bar(position = position_fill()) + # use bars
  coord_polar(theta = "y") + # polar coordinates
  facet_wrap(~program) + # facet wrap on program
  theme_void() # blank theme for pie charts

```
