---
title: "DSO Faculty Award"
author: "Andy Grogan-Kaylor"
date: "2021-05-27"
categories: [news]
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

I was pleased to learn that I was chosen as this year's recipient of the University of Michigan School of Social Work Doctoral Student Faculty Award. 

Here are some excerpts from the award letter: 

> "Since 2019, DSO has created a faculty award to honor one professor that the doctoral students will collectively select for recognition. There are so many faculty members who are particularly supportive of doctoral students but may not always receive school-wide recognition. The 2019 DSO Faculty Award went to Dr. Karen Staller. "

> "It is my honor to announce that Dr. Andy Grogan-Kaylor has been chosen as this year’s recipient of the DSO Faculty Award." 

> "For years, Andy single-handedly taught the only quantitative courses available to SW Doc students. He's super thoughtful in his approach to the course, both making it relevant and tailored to each student. He spent each and every week producing extremely high-quality material that remains a valuable resource to me years later. I am always impressed at how he scaffolds the material for those who struggle with statistics and for those who are pretty advanced. Even now, I would feel completely comfortable reaching out to Andy with any data visualization or statistical analysis questions."

> "Andy has made a huge impact on me during my doctoral studies. I have had the pleasure of working with Andy directly and taking multiple courses from him. From both a mentorship and teaching capacity, Andy is kind, warm, and thoughtful. During his quantitative courses, Andy had a way of making us feel intelligent and valued, even when we were grappling with the difficulties of attempting to understand complex quantitative methodology. Andy would also revise and improve upon course material as a result of conversations with his students, which I felt showed his humility and respect for us. I think anyone who has taken one of Andy’s courses feels like they could email him or stumble into his office to chat anytime. He’s such a great human being, and greatly deserves this honor!"

> "Andy is well-deserving of this award. He has taught and mentored many of us doctoral students. His approach to teaching methods courses is engaging for students across a range of methodological backgrounds. His courses help us see how methods can be leveraged as a tool to advance social justice. In addition to supporting students through teaching, Andy provides a great deal of support outside the classroom. Throughout my years in the program, I have consistently noticed that doctoral students go to Andy with complex methodological questions. We always come away better equipped to move forward with our research. He has eased our anxieties through his approachability and empathy, and he has empowered us with essential knowledge and skills on our PhD journey. When I think of what kind of faculty mentor I would like to be someday, the first thing that comes to mind is 'I want to be like Andy.'"

> "I have taken multiple statistical analysis classes throughout my academic career and yet always struggled with quantitative methods. That changed when I arrived in Prof. Grogan-Kaylor’s class. He has the unique ability of taking a complicated topic and breaking it down into a way that makes it easy to understand. He is patient and encouraging; he never makes a student feel that they are asking a dumb question. He is approachable and committed to making the skills learned in class applicable to student’s work." 

> "Prof. Grogan-Kaylor is an exceptional instructor and by far the best quantitative methods instructor I have ever had.  As the sole instructor who offers doctoral-level quantitative training courses in Social Work, he is truly an asset to the school. He cares about his students, is patient, thorough (he consistently explains the intuition behind the methods in order to facilitate learning), approachable, and overall just genuinely interested in helping students reach their academic and professional potential. This award is well-deserved! "

> "Congratulations Dr. Grogan-Kaylor!" 