---
title: "New Articles With UNICEF MICS Data"
description: |
  New articles on parenting and child development in global context.
author:
  - name: Andy Grogan-Kaylor 
    url: https://agrogan1.github.io/
    affiliation: University of Michigan
    affiliation_url: https://umich.edu/
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

library(maps) # maps

library(maptools) # maptools

library(leaflet) # web maps

library(sp) # spatial data

library(countrycode) # manipulate country names and codes

library(dplyr) # data wrangling

library(tidyr) # tidy data

library(sf) # simple features

```

```{r}

data(wrld_simpl) # world map data

global_data <- st_as_sf(wrld_simpl) %>% # make an sf dataset
  select(-POP2005) # remove POP2005

# get MICS countries

country <- c("Afghanistan", "Algeria",  "Argentina",  
             "Bangladesh",  "Barbados",  "Belarus",  
             "Belize",  "Benin",  "Bosnia and Herzegovina",  
             "Cameroon",  "Central African Republic",  "Chad",  
             "Democratic Republic of the Congo",  
             "Republic of the Congo",  
             "Costa Rica",  "Cote d'Ivoire",  
             "Dominican Republic",  
             "El Salvador",  "Eswatini",  "Ghana",  
             "Guinea",  "Guinea Bissau",  "Guyana",  
             "Iraq",  "Jamaica",  "Kazakhstan",  
             "Kenya",  "Kosovo",  "Kyrgyzstan",  
             "Laos", "Macedonia",  "Madagascar",  
             "Malawi",  "Mali",  "Mauritania",  
             "Mexico",  "Moldova",  "Mongolia",  
             "Montenegro",  "Nepal",  "Nigeria",  
             "Pakistan",  "Panama",  "Paraguay",  
             "Sao Tome and Principe",  "Senegal",  "Serbia",  
             "Sierra Leone",  "Somalia",  "St. Lucia",  
             "State of Palestine",  "Suriname",  "Thailand",  
             "The Gambia",  "Togo",  "Trinidad and Tobago",  
             "Tunisia",  "Turkmenistan",  "Ukraine",  
             "Uruguay",  "Vietnam",  "Zimbabwe")

# convert to ISO3

country_iso <- countrycode(country, 
                           'country.name', 
                           'iso3c')

# MICS is an sf object that is subset of global_data

MICS <- global_data %>% 
  filter(ISO3 %in% country_iso)
  
```

We have published some new articles with the UNICEF Multiple Indicator Cluster Survey (MICS) data: [https://agrogan1.github.io/#multiple-indicator-cluster-surveys-mics-unicef-data](https://agrogan1.github.io/#multiple-indicator-cluster-surveys-mics-unicef-data)

This research is conducted in collaboration with colleagues [Shawna Lee](https://www.parentingincontext.org/), [Julie Ma](https://poverty.umich.edu/research/faculty-experts/julie-ma/), [Kaitlin Ward](https://www.kaitlinpward.com/), [Garrett Pace](https://www.garrettpace.com/), and [Jorge Cuartas](https://scholar.harvard.edu/jorgecuartas/home).


```{r, fig.cap="Locations of Countries in MICS", fig.height=3}

library(leaflet)

leaflet() %>%
  setView(0, 25, zoom = 1.5) %>%
  addProviderTiles(providers$Stamen.Terrain) %>%
  addPolygons(data = MICS, 
              fillOpacity = .75, 
              color = "#5b92e5", 
              label = MICS$NAME,
              highlightOptions = highlightOptions(color = "red", 
                                                  weight = 2,
                                                  bringToFront = TRUE)) 

```











