---
title: "Proportion of Children Protected from Corporal Punishment"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output: 
  html_document: 
    highlight: haddock
    number_sections: yes
    toc: yes
    code_folding: hide
    code_download: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

```

# Graphic

```{r}

library(ggplot2)

library(waffle)

library(hrbrthemes)

library(extrafont)

```


```{r}

# set up data

cpdata <- data.frame(parts=c("protected", "not protected"),
                     vals = c(13, 87))

# make parts a factor

cpdata$parts <- factor(cpdata$parts,
                       levels = c("protected", "not protected"))


```

```{r, fig.height=6}

ggplot(cpdata,
       aes(color = parts,
           values = vals)) +
  geom_pictogram(aes(label = parts),
                 make_proportional = TRUE) +
  scale_label_pictogram(name = NULL,
                        values = c("male", "male"),
                        labels = c("protected", "not protected")) +
  scale_color_manual(values = c("blue", 
                                "grey"),
                     name=NULL) +
  # geom_waffle(size = .1, color = "white")  +
  coord_equal() +
  # facet_wrap(~parts, nrow = 1, strip.position = "bottom") +
  labs(title = "Of every 100 Children In The World",
       subtitle = "Only 13 Are Protected From Corporal Punishment In All Settings",
       caption = "Source: https://endcorporalpunishment.org/countdown/") +
  theme_ipsum_rc(grid="") +
  theme_enhance_waffle() +
  theme(axis.ticks = element_blank(),
        legend.key.size = unit(3,"line")) 

```

# Source

Source: [https://endcorporalpunishment.org/countdown/](https://endcorporalpunishment.org/countdown/)

