---
title: "Quick Look At How Dates Work in R"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output: 
  html_document: 
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      warning = FALSE,
                      message = FALSE)

```

# Background

[https://www.statmethods.net/input/dates.html](https://www.statmethods.net/input/dates.html)

# Demo

## Libraries

```{r}

library(lubridate) # easier to work with dates

```

## Fake Data

Make up some simulated data for demonstration purposes.

```{r}

startdate <- c("2019-01-01", 
                "2019-02-15",
                "2019-03-01")

enddate <- c("2019-1-30",
              "2019-5-30",
              "2019-4-30")

```

## Format As Dates

Format these quantities as dates so that R understands that they are dates.

```{r}

startdate <- ymd(startdate) # format as dates

enddate <- ymd(enddate) # format as dates

```

## Calculate Duration

Subtract `startdate` from `enddate` to calculate duration.

```{r}

howlong <- enddate - startdate # calculate duration

```

## Test Length of Duration

Use the `variable[test]` syntax to figure out if duration is longer than 90 days.

```{r}

mydata <- data.frame(startdate, enddate, howlong) # bundle into a data set

mydata$over90 <- "no"  # initialize to "no"

mydata$over90[mydata$howlong > 90] <- "yes"

mydata # replay data set

```

