---
title: "Reshaping Data in R With tidyr"
author:
  - name: "Andrew Grogan-Kaylor"
    url: https://umich.edu/~agrogan
    affiliation: University of Michigan
    affiliation_url: https://www.umich.edu
date: "`r Sys.Date()`"
output:
  html_document:
    fig_height: 3
    highlight: haddock
    keep_md: no
    number_sections: yes
    theme: default
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  radix::radix_article:
    toc: true
    number_sections: yes
    toc_depth: 2
    fig_height: 3
citation_url: https://agrogan1.github.io/myposts/
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Background

This is a very quick post on reshaping data in R, using `tidyr`.

```{r}

library(tidyr) # tidy data

```

# Simulate Some Wide Data

```{r}

# simulated wide data

parent <- c(1,2,3) # parent id

child1 <- c(4,5,6) # first child

child2 <- c(7,8,9) # second child

mydata <-data.frame(parent, child1, child2)

mydata # replay mydata

```

# Reshape The Data To Long Format


```{r}

# reshape data with gather

myReshapedData <- gather(mydata, # dataframe
                         key, # name of column for key
                         value, # name of column for value
                         2:3) # columns to gather

myReshapedData # replay myReshapedData

```

