---
title: "Theming in ggplot"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
    code_folding: hide 
  html_document:
    fig_height: 3
    highlight: haddock
    number_sections: yes
    theme: default
    code_folding: hide 
    code_download: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  pdf_document: 
    fig_caption: yes
    highlight: haddock
    latex_engine: xelatex
    number_sections: yes
    toc: yes
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)

```


# Get The Data

> In the HTML version, click on the `hide` buttons to see the code.

```{r}

data("iris") # famous iris flower data

```

# Load The `ggplot` Library

```{r}

library(ggplot2)

```

# Basic ggplot Graph

```{r}

p0 <- ggplot(iris,
             aes(x = Petal.Length, # x is petal length
                 y = Sepal.Length, # y is sepal length
                 color = Species)) + # color is species
  geom_point() + # use points
  geom_smooth() + # use smoother
  labs(title = "Sepal Length by Petal Length",
       subtitle = "by Species",
       x = "Petal Length",
       y = "Sepal Length") 

p0 # replay

```

# Add A Built-In Theme and Built-In Color Scheme

```{r}

p0 + 
    scale_color_viridis_d() + # viridis color palette
    theme_minimal() # minimal (built-in) theme

```

# Add More Modifications Using `theme()`

```{r}

p0 + 
  scale_color_viridis_d() + # viridis color palette
  theme_minimal() + # minimal "preset" theme 
  theme(plot.title = element_text(size = 20,), # larger title
        plot.subtitle = element_text(size = 18, # larger subtitle
                                     color = "grey"), # grey subtitle
        axis.text.x = element_text(angle = -45), # rotate x axis labels
        axis.text.y = element_text(angle = 45, # rotate y axis labels
                                   color = "red")) # y axis label color



```


