---
title: "You Have To Get Your Data From Somewhere"
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  tufte::tufte_html: 
    css: myTufteCSS.css
    highlight: haddock
    number_sections: yes
    toc: yes
  html_document:
    css: UM.css
    fig_height: 3
    highlight: haddock
    number_sections: yes
    toc: yes
    toc_float:
      collapsed: yes
      smooth_scroll: yes
  tufte::tufte_handout:
    number_sections: yes
    toc: yes
  tint::tintPdf:
    toc: no
  pdf_document:
    toc: no
header-includes: \usepackage{xcolor}
---

```{r setup, include=FALSE}

library(tint)

# invalidate cache when the package version changes

knitr::opts_chunk$set(tidy = FALSE, 
                      cache.extra = packageVersion('tint'))

options(htmltools.dir.version = FALSE)

```

# You Have To Get Your Data From Somewhere

> In learning R, as well as RMarkdown, one of the most difficult tasks seems to be understanding how to import data.

> Read your data into a dataset using the *right function* for the *right format* from the *correct location*.

# Basic Idea

`mydata`[^1] `<- function`[^2]`("path/to/`[^3]`file.extension`[^4]`")`

[^1]: How R will refer to your data. R's *nickname* for your data.

[^2]: The correct function for the type of data you are reading in, e.g. RData, CSV, Excel.

[^3]: Where is your data located? The *path* to your data.

[^4]: What is the *filename* of the file containing your data? Note that the extension often tells you *what kind* of data this is.

# Examples

## Data Already in R Format

```{r, eval=FALSE}

mydata <- load("/project1/mydata.RData") # load data in R format

```


## Data in CSV

```{r, eval=FALSE}

library(readr) # library to read CSV

dataset <- read_csv("/project1/mydata.csv")

```


## Data in Excel

```{r, eval=FALSE}

library(readxl) # library to read Excel

dataset <- read_excel("/project1/mydata.xlsx")

```




 

